version: '3'

services: 
    www:
        image:  nginx:latest        
        networks:
            - stacknet
        deploy:
            replicas: 4
        ports:
            - 80:80

    alp:
        image:  alpine:latest
        command: ["sh","-c","nslookup www ; tail -f /dev/null"]
        networks:
            - stacknet
        deploy:
            replicas: 1
            placement:
                constraints: [node.role == manager]
        depends_on:
            - www

networks:
    stacknet:

volumes:
    stackdata:

