version: '3'

services: 
    www:
        image:  nginx:latest        
        network:
            - stacknet
        deploy:
 	    replicas: 4
        ports:
            - 80:80

    alp:
        image:  alpine:latest
        network:
            - stacknet
        deploy:
            replicas: 1
            placement:
                constraints: [node.role == manager]
        depends_on:
            - db

networks:
    stacknet:

volumes:
    stackdata:

		- 
