#! /bin/bash

echo "Launching/creating a private bridged network for local containers to communicate with one another securely"
echo "Removed if previous MYBRIDGE existed"

sudo -- docker network rm MYBRIDGE
sudo -- docker network create MYBRIDGE
sudo -- docker network inspect MYBRIDGE
sudo -- docker network ls

echo "A docker bridge was created, called MYBRIDGE"
