#! /bin/bash
echo "Preparing an Amazon Linux AMI to be used as a docker container"

sudo -- yum -y update
sudo -- yum -y install docker
sudo -- service docker start
sleep 2
sudo -- docker version
sudo -- docker run hello-world
echo "Docker installed"


