#!/bin/bash

# Rebuild image
docker build -t node-dev .

# Development content
docker volume create app

# Production content
docker volume create dist


# Create a demo app, called my-app
docker run -it -v app:/my-app  -p 4200:4200 --name node-dev node-dev

# Serve on port 4200 a live server
docker run -d -v app:/my-app -p 4200:4200 --name live-serv node-dev ng serve --host 0.0.0.0 --port 4200

# compile demo app
docker run -it --rm  -v app:/my-app -v dist:/dist --name compil node-dev bash -c "cd /my-app && ng build --prod && mv /my-app/dist/* /dist" 

# run aot-compiled in nginx
docker run -d -p 80:80 -v dist:/usr/share/nginx/html:ro --name nginx nginx


# test
firefox http://localhost:4200
firefox http://localhost




