#!/bin/bash

# Rebuild images
./buildAll


# Development content
docker volume create app

# Production content
docker volume create dist


# Create a demo app, called my-app - by default, files created are owned by 1000, but image runs as root
docker run -it -v app:/my-app  -p 4200:4200 --name node-dev xg/node-dev

# edit with atom - all GUI apps need to run as user 1000 !
docker run -it --rm -v /tmp:/tmp -v app:/workdir -e DISPLAY xg/atom 

# Serve on port 4200 a live server, user root
docker run -d -v app:/my-app -p 4200:4200 --name live-serv xg/node-dev ng serve --host 0.0.0.0 --port 4200

# compile demo app, user root
docker run -it --rm  -v app:/my-app -v dist:/dist --name compil xg/node-dev bash -c "cd /my-app && ng build --prod && mv /my-app/dist/* /dist" 

# run aot-compiled in nginx, user root
docker run -d -p 80:80 -v dist:/usr/share/nginx/html:ro --name nginx nginx



# test
firefox http://localhost:4200
firefox http://localhost




